### ISSUE TITLE
Python 3 : xrange not defined

### ISSUE THREAD

**Issue by chir-set** [lassoan/SlicerLineProfile#3]
Since Python 3 being the default in Slicer, this error is recorded in stdout :

Traceback (most recent call last):
  File "/home/user/Documents/Slicer4/Custom_Ext/LineProfile/LineProfile.py", line 156, in onApplyButton
    logic.run(self.inputVolumeSelector.currentNode(), self.inputRulerSelector.currentNode(), self.outputArraySelector.currentNode(), lineResolution)
  File "/home/user/Documents/Slicer4/Custom_Ext/LineProfile/LineProfile.py", line 197, in run
    self.updateOutputArray(inputVolume,inputRuler,outputArray,lineResolution)
  File "/home/user/Documents/Slicer4/Custom_Ext/LineProfile/LineProfile.py", line 265, in updateOutputArray
    x = xrange(0, probedPoints.GetNumberOfPoints())
NameError: name 'xrange' is not defined

After a quick web search, changing 'xrange' for 'range' restores normal operations.

Perhaps an inline Python version check should direct to the right function to use ?

**Comment by lassoan** [comment]
Thank you, I've fixed the Python3 compatibility issue
